In [8]:
import numpy as np

In [26]:
a=np.array([2,3,4,5,6,9])
c=np.array([4,6,7,4,8,2])

In [61]:
a+c

array([ 6,  9, 11,  9, 14, 11])

In [7]:
a<5

array([ True,  True,  True, False, False, False])

In [17]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [65]:
np.concatenate((a,c))

array([2, 3, 4, 5, 6, 9, 4, 6, 7, 4, 8, 2])

In [14]:
a*2

array([ 4,  6,  8, 10, 12, 18])

In [66]:
a*c

array([ 8, 18, 28, 20, 48, 18])

In [27]:
a=np.reshape(a,(3,2))
c=np.reshape(c,(3,2))

In [68]:
a

array([[2, 3],
       [4, 5],
       [6, 9]])

In [71]:
c

array([[4, 6],
       [7, 4],
       [8, 2]])

In [72]:
a*c

array([[ 8, 18],
       [28, 20],
       [48, 18]])

In [52]:
np.random.randn(10)

array([ 0.92256747,  1.03593512,  0.88025238, -0.12328054, -0.72662715,
       -0.07697551,  1.45464664,  1.33261347, -0.21300527,  1.64546262])

In [55]:
np.random.randint(4)

3

In [56]:
np.random.rand(3)

array([0.10537373, 0.22181917, 0.73015205])

In [64]:
arr=np.linspace(1,15,4) # gives value between 1 and 15 with the gap of 4)
arr

array([ 1.        ,  5.66666667, 10.33333333, 15.        ])

In [76]:
a.shape

(3, 2)

In [79]:
a.sum(axis=1)[0] # row axis =1 and column axis =0

5

In [9]:
h=np.array([[4,5,5],[4,7,8]])

In [10]:
h.flatten()

array([4, 5, 5, 4, 7, 8])

In [11]:
g=np.array([[8,0,4],[3,5,8]])

In [12]:
g.ravel() # it is memeory efficient than flatten

array([8, 0, 4, 3, 5, 8])

In [13]:
a1=np.array([1,2,3,4,5,6])

In [17]:
a1*10

array([10, 20, 30, 40, 50, 60])

In [20]:

A = np.array([[2, 4],
              [6, 8]])

B = np.array([[1, 3],
              [5, 7]])

print(A @ B)# this for matrix multification
print(A*B) # this is for simple multiplication

[[22 34]
 [46 74]]
[[ 2 12]
 [30 56]]


In [29]:
a.T #it creates transpose

array([[2, 4, 6],
       [3, 5, 9]])

In [31]:
np.eye(3) # it creates identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])